name: simple_app
description: Package to simplify application creation with a standard structure
version: 1.0.0
author: Ricardo Crescenti <ricardo.crescenti@gmail.com>
homepage: https://github.com/ricardocrescenti/flutter-simple-app

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  module_provider: ^2.1.1
    # path: '..\flutter-module-provider'
    # git: 
    #   url: https://github.com/ricardocrescenti/flutter-module-provider.git
    #   ref: dev
  simple_localization: ^1.2.1
  simple_form: #^1.0.0
    # path: '..\flutter-simple-form'
    git: 
      url: https://github.com/ricardocrescenti/flutter-simple-form.git
      ref: master
  standard_dialogs: ^1.0.0
    # path: '..\flutter-standard-dialogs'
    # git: 
    #   url: https://github.com/ricardocrescenti/flutter-standard-dialods.git
    #   ref: master
  useful_widgets: #^1.0.0
    # path: '..\flutter-useful-widgets'
    git: 
      url: https://github.com/ricardocrescenti/flutter-useful-widgets.git
      ref: dev

  localstorage: ^3.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
